task#p001_login-markup
emily0604/frontend-standard pull request #18
Opened 2017-10-19 08:45 UTC by spideyinf

p001-login-markup

2017-10-19 08:46 UTC, emily0604 requested changes

2017-10-19 08:46 UTC, emily0604 commented on source/p001-login.pug
> +            div.p001-login__inputs
remove div

2017-10-19 08:46 UTC, emily0604 commented on source/sass/components/_ui-elements.scss
> +    background-repeat: no-repeat;
please check indent

2017-10-19 08:46 UTC, emily0604 commented on source/sass/pages/p001-login.scss
> +.p001-login__inputs {
using  nested loop

2017-10-19 09:18 UTC, emily0604 requested changes

2017-10-19 09:18 UTC, emily0604 commented on source/p001-login.pug
> +              +button('login', 'anchor').btn-gradient-primary.btn-block
not using gradient for name.

2017-10-19 09:18 UTC, emily0604 commented on source/p001-login.pug
> +                u Sign up here
u? what is u?

2017-10-19 09:18 UTC, emily0604 commented on source/p001-login.pug
> +              +button('login', 'anchor').btn-gradient-primary.btn-block
please check mixin button again . 
```
mixin button(label, link, icon)
  if typeof link !== 'undefined' && link === 'anchor'
    a(href='#').btn&attributes(attributes)
      if typeof icon !== 'undefined' && icon !== ''
        i(class=icon).btn__icon
      span.text= label
  else
    button.btn&attributes(attributes)
      if typeof icon !== 'undefined' && icon !== ''
        i(class=icon).btn__icon
      span.text= label
```

2017-10-19 09:30 UTC, spideyinf commented on source/p001-login.pug
> +                u Sign up here
This is a html tag underline

2017-10-23 03:16 UTC, emily0604 approved these changes

2017-10-23 03:17 UTC, merged